#!/usr/bin/env bash

# fix segmentation fault reported in https://github.com/k2-fsa/icefall/issues/674
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

set -eou pipefail

export PYTHONPATH="$PWD/../icefall${PYTHONPATH:+:$PYTHONPATH}"

nj=15
# run step 0 to step 5 by default
stage=0
stop_stage=3

train_dataset_candidates=("train" "VietMed" "ViMedCSS")
eval_dataset_candidates=("dev" "test")

# Note: This script just prepare the minimal requirements that needed by a
# transducer training with bpe units.
#
# If you want to use ngram or nnlm, please continue running prepare_lm.sh after
# you succeed running this script.
#
# This script also contains the steps to generate phone based units, but they
# will not run automatically, you can generate the phone based units by
# bash prepare.sh --stage -1 --stop-stage -1
# bash prepare.sh --stage 6 --stop-stage 6


# We assume dl_dir (download dir) contains the following
# directories and files. If not, they will be downloaded
# by this script automatically.

dl_dir=$PWD/download

. shared/parse_options.sh || exit 1

# vocab size for sentence piece models.
# It will generate data/lang_bpe_xxx,
# data/lang_bpe_yyy if the array contains xxx, yyy
vocab_sizes=(
  # 5000
  2000
  # 1000
  # 500
)

# All files generated by this script are saved in "data".
# You can safely remove "data" and rerun this script to regenerate it.
mkdir -p data

log() {
  # This function is from espnet
  local fname=${BASH_SOURCE[1]##*/}
  echo -e "$(date '+%Y-%m-%d %H:%M:%S') (${fname}:${BASH_LINENO[0]}:${FUNCNAME[1]}) $*"
}

log "Running prepare.sh"

log "dl_dir: $dl_dir"

existing_train_parts=()
for part in "${train_dataset_candidates[@]}"; do
  if [ -d "$dl_dir/$part" ]; then
    existing_train_parts+=("$part")
  fi
done

existing_eval_parts=()
for part in "${eval_dataset_candidates[@]}"; do
  if [ -d "$dl_dir/$part" ]; then
    existing_eval_parts+=("$part")
  fi
done

dataset_parts=("${existing_eval_parts[@]}" "${existing_train_parts[@]}")

if [ ${#existing_train_parts[@]} -eq 0 ]; then
  log "No training dataset found under $dl_dir. Expected one of: ${train_dataset_candidates[*]}"
  exit 1
fi

if [ ${#dataset_parts[@]} -eq 0 ]; then
  log "No dataset split found under $dl_dir"
  exit 1
fi

train_dataset_parts="${existing_train_parts[*]}"
all_dataset_parts="${dataset_parts[*]}"

log "Using train dataset parts: $train_dataset_parts"
log "Using all dataset parts for manifests/fbank: $all_dataset_parts"


if [ $stage -le 1 ] && [ $stop_stage -ge 1 ]; then
  log "Stage 1: Prepare supervised manifest"
  # We assume that you have downloaded the supervised corpus
  # to $dl_dir/supervised
  mkdir -p data/manifests
  if [ ! -e data/manifests/.supervised.done ]; then
    python3 local/prepare_manifest.py --num-jobs $nj --corpus-dir $dl_dir --output-dir data/manifests --language vietnamese --dataset-parts "$all_dataset_parts"
    touch data/manifests/.supervised.done
  fi
fi

if [ $stage -le 2 ] && [ $stop_stage -ge 2 ]; then
  log "Stage 2: Compute fbank"
  mkdir -p data/fbank
  if [ ! -e data/fbank/.supervised.done ]; then
    python3 ./local/compute_fbank.py --dataset "$all_dataset_parts" --use-executor false
    touch data/fbank/.supervised.done
  fi
fi

if [ $stage -le 3 ] && [ $stop_stage -ge 3 ]; then
  log "Stage 3: Prepare BPE based lang"

  for vocab_size in ${vocab_sizes[@]}; do
    lang_dir=data/lang_bpe_${vocab_size}
    mkdir -p $lang_dir

    if [ ! -f $lang_dir/transcript_words.txt ]; then
      log "Generate data for BPE training"
      : > $lang_dir/transcript_words.txt
      for part in "${existing_train_parts[@]}"; do
        files=$(
          find -L "$dl_dir/$part" -name "*.trans.txt"
        )
        for f in ${files[@]}; do
          cut -d " " -f 2- "$f" >> $lang_dir/transcript_words.txt
        done
      done
    fi

    if [ ! -f $lang_dir/bpe.model ]; then
      python3 ./local/train_bpe_model.py \
        --lang-dir $lang_dir \
        --vocab-size $vocab_size \
        --transcript $lang_dir/transcript_words.txt
    fi
  done
fi
